[package]
name = "life"
version = "0.1.0"
authors = ["brundolf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.107.0"
crossbeam = "0.7.3"

[profile.dev]
# opt-level = 3